BEGIN TRANSACTION;

    DROP TABLE FUNCIONARIO;
    DROP TABLE ESTUDANTE;
    DROP TABLE USUARIO;
    DROP TABLE IES;

    DROP DOMAIN EMAIL;

    DROP TYPE GENERO;
    DROP TYPE TIPO_USUARIO;

COMMIT;